/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as CustomizeIndexRouteImport } from './routes/customize.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CustomizeRationBoxRouteImport } from './routes/customize.ration-box'
import { Route as CustomizeMasalaRouteImport } from './routes/customize.masala'
import { Route as CustomizeGiftHamperRouteImport } from './routes/customize.gift-hamper'
import { Route as CustomizeDalMixRouteImport } from './routes/customize.dal-mix'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeIndexRoute = CustomizeIndexRouteImport.update({
  id: '/customize/',
  path: '/customize/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRationBoxRoute = CustomizeRationBoxRouteImport.update({
  id: '/customize/ration-box',
  path: '/customize/ration-box',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeMasalaRoute = CustomizeMasalaRouteImport.update({
  id: '/customize/masala',
  path: '/customize/masala',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeGiftHamperRoute = CustomizeGiftHamperRouteImport.update({
  id: '/customize/gift-hamper',
  path: '/customize/gift-hamper',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeDalMixRoute = CustomizeDalMixRouteImport.update({
  id: '/customize/dal-mix',
  path: '/customize/dal-mix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customize/dal-mix': typeof CustomizeDalMixRoute
  '/customize/gift-hamper': typeof CustomizeGiftHamperRoute
  '/customize/masala': typeof CustomizeMasalaRoute
  '/customize/ration-box': typeof CustomizeRationBoxRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/customize/': typeof CustomizeIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customize/dal-mix': typeof CustomizeDalMixRoute
  '/customize/gift-hamper': typeof CustomizeGiftHamperRoute
  '/customize/masala': typeof CustomizeMasalaRoute
  '/customize/ration-box': typeof CustomizeRationBoxRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/customize': typeof CustomizeIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customize/dal-mix': typeof CustomizeDalMixRoute
  '/customize/gift-hamper': typeof CustomizeGiftHamperRoute
  '/customize/masala': typeof CustomizeMasalaRoute
  '/customize/ration-box': typeof CustomizeRationBoxRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/customize/': typeof CustomizeIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customize/dal-mix'
    | '/customize/gift-hamper'
    | '/customize/masala'
    | '/customize/ration-box'
    | '/product/$slug'
    | '/shop/$category'
    | '/customize/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customize/dal-mix'
    | '/customize/gift-hamper'
    | '/customize/masala'
    | '/customize/ration-box'
    | '/product/$slug'
    | '/shop/$category'
    | '/customize'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/customize/dal-mix'
    | '/customize/gift-hamper'
    | '/customize/masala'
    | '/customize/ration-box'
    | '/product/$slug'
    | '/shop/$category'
    | '/customize/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomizeDalMixRoute: typeof CustomizeDalMixRoute
  CustomizeGiftHamperRoute: typeof CustomizeGiftHamperRoute
  CustomizeMasalaRoute: typeof CustomizeMasalaRoute
  CustomizeRationBoxRoute: typeof CustomizeRationBoxRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  CustomizeIndexRoute: typeof CustomizeIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize/': {
      id: '/customize/'
      path: '/customize'
      fullPath: '/customize/'
      preLoaderRoute: typeof CustomizeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize/ration-box': {
      id: '/customize/ration-box'
      path: '/customize/ration-box'
      fullPath: '/customize/ration-box'
      preLoaderRoute: typeof CustomizeRationBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize/masala': {
      id: '/customize/masala'
      path: '/customize/masala'
      fullPath: '/customize/masala'
      preLoaderRoute: typeof CustomizeMasalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize/gift-hamper': {
      id: '/customize/gift-hamper'
      path: '/customize/gift-hamper'
      fullPath: '/customize/gift-hamper'
      preLoaderRoute: typeof CustomizeGiftHamperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize/dal-mix': {
      id: '/customize/dal-mix'
      path: '/customize/dal-mix'
      fullPath: '/customize/dal-mix'
      preLoaderRoute: typeof CustomizeDalMixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomizeDalMixRoute: CustomizeDalMixRoute,
  CustomizeGiftHamperRoute: CustomizeGiftHamperRoute,
  CustomizeMasalaRoute: CustomizeMasalaRoute,
  CustomizeRationBoxRoute: CustomizeRationBoxRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  CustomizeIndexRoute: CustomizeIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
